services:
  postgres:
    image: postgres:15-alpine

    container_name: dam-postgres

    restart: always

    env_file:
      - .env

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

    volumes:
      - postgresData:/var/lib/postgresql/data

    networks:
      - dam-network

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  gateway-api:
    build:
      context: .
      dockerfile: Docker/gateway.Dockerfile

    env_file:
      - .env

    restart: always

    ports:
      - '8000:8000'

    networks:
      - dam-network

  # =========== NGINX =============

  nginx:
    image: nginx:alpine

    container_name: dam-nginx

    depends_on:
      - gateway-api

    ports:
      - '80:80'

    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

    restart: always

    networks:
      - dam-network

volumes:
  postgresData:

networks:
  dam-network:
